import {
  bytesToHex,
  concatBytes,
  randomBytes,
  utf8ToBytes,
} from "@noble/hashes/utils";
import { sha256 } from "@noble/hashes/sha256";
import { bls12_381 as bls } from "@noble/curves/bls12-381";
import * as readline from "node:readline/promises";
import { stdin, stdout } from "node:process";
import * as vx from "./vx";

import {
  CommitmentContext,
  MessageContext,
  computeBOBRouletteResult,
} from "verifier";

import { assert } from "tsafe";

const clientSeed = "chicken"; // Note: this is treated as ascii, normally this would be generated by a seeding event...

async function main() {
  console.log("Running vx roulette demo...");

  // First lets generate a hash chain
  const hashChainLength = 11;
  let iterator = randomBytes(32); // very secret!

  const hashChain: Uint8Array[] = [];
  for (let i = 0; i < hashChainLength; i++) {
    hashChain.push(iterator);
    iterator = sha256(iterator);
  }
  // We won't reverse the hash chain, as we'll iterate by poping off the last element

  const commitment = hashChain.pop();
  assert(commitment !== undefined);
  console.log(
    "Our hash chain has been established. The terminating hash is: ",
    bytesToHex(commitment)
  );

  const commitmentContext: CommitmentContext = { sha256Chain: {} };
  const VX_PUBKEY = await vx.make_commitment(commitment, commitmentContext);

  console.log(
    `Hey Player! We're ready to go with the following values: 
    COMMITMENT := ${bytesToHex(commitment)}
    VX_PUBKEY    := ${bytesToHex(VX_PUBKEY)}
    Please see:  https://provablyhonest.com/apps/demo/vx/summary/${bytesToHex(
      commitment
    )}
    `
  );

  let gameId = 0;
  let hash = commitment;
  assert(hash !== undefined);

  const rl = readline.createInterface({ input: stdin, output: stdout });

  while (hashChain.length >= 1) {
    gameId++;

    const moveChoice = await rl.question(
      `[${gameId}] Do you want to bet on (B) Black or (O) Orange or ($) bonus  Or X to quit: `
    );

    const wager: MessageContext = {
      bobRoulette: {
        blackBets: [],
        orangeBets: [],
        bonusBets: [],
      },
    };

    if (moveChoice.toLowerCase() === "b") {
      wager.bobRoulette!.blackBets.push({
        uname: "keyboard",
        amount: { value: 1, currency: 0 },
      });
    } else if (moveChoice.toLowerCase() === "o") {
      wager.bobRoulette!.orangeBets.push({
        uname: "keyboard",
        amount: { value: 1, currency: 0 },
      });
    } else if (moveChoice === "$") {
      wager.bobRoulette!.bonusBets.push({
        uname: "keyboard",
        amount: { value: 1, currency: 0 },
      });
    } else if (moveChoice.toLowerCase() === "x") {
      break;
    }

    // obviously normally there would be a lot more bets

    const message = concatBytes(hash, utf8ToBytes(clientSeed));
    const vxSignature = await vx.make_message(
      commitment,
      message,
      gameId,
      wager
    );

    const verified = bls.verify(vxSignature, message, VX_PUBKEY);
    if (!verified) {
      throw new Error("huh?! vx gave us something that didn't verify");
    }

    // Now let's compute the result of the game
    const res = computeBOBRouletteResult(vxSignature);
    console.log(`Game id ${gameId} = ${res} `);

    // Now let's get the next hash for our game
    const h = hashChain.pop();
    assert(h !== undefined); // Hack to make TS happy
    hash = h;
  }
  rl.close();

  // There's really no point revealing, because each game reveals the previous anyway
  // but technically we probably should have a special reveal for after-the-last game
}

main();
